owner: fipsign
repo: status

sites:
  - name: PQ-Sign API
    url: https://api.fipsign.dev/health
  - name: PQ-Sign Dashboard
    url: https://app.fipsign.dev
  - name: PQ-Proxy API
    url: https://proxy-api.fipsign.dev/health
  - name: PQ-Proxy Core
     url: https://test.nox-pay.com

status-website:
  cname: status.fipsign.dev
  name: FIPSign Status
  logoUrl: https://fipsign.dev/assets/logo.svg
  introTitle: FIPSign Status
  introMessage: Real-time uptime monitoring for FIPSign services.
gh-token: ${{ secrets.GH_PAT }}
